### ISSUE TITLE
对楼主提个建议吧

### ISSUE THREAD

**Issue by ghost** [developerHaoz/WatermelonDiaryNew#1]
App挺不错的 建议采用mvp 可以参考下google todolist demo

**Comment by developerHaoz** [comment]
多谢提出的建议，等改天有空试着用mvp重构一遍

**Comment by LoveqLRC** [comment]
建议引入富文本编辑，支持图片，视频等

**Comment by developerHaoz** [comment]
这个想法不错，纯文字确实有点低调，多谢建议。

**Comment by misakuo** [comment]
富文本涉及面非常广，等楼主实现完估计就能祝女神新婚快乐了 😆

**Comment by developerHaoz** [comment]
老哥，你这大实话，说的有点扎心啊。

**Comment by EvanKo** [comment]
有意思

**Comment by skywalkerhbz** [comment]
有意思

**Comment by hellohanyu** [comment]
@developerHaoz 膜拜鹅厂大佬

**Comment by Coraxl** [comment]
楼主，为什么我下载下来实现不了啊。好郁闷

**Comment by joycaf** [comment]
Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method implementation() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
	at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:182)
	at org.gradle.internal.metaobject.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:89)
	at build_110a6jhrbdrez539prz5pu5yb$_run_closure2.doCall(E:\WatermelonDiaryNew-master\app\build.gradle:23)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
	at org.gradle.util.ConfigureUtil.configureTarget(ConfigureUtil.java:160)
	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:106)
	at org.gradle.api.internal.project.DefaultProject.dependencies(DefaultProject.java:1002)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.invokeMethod(BeanDynamicObject.java:382)
	at org.gradle.internal.metaobject.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:170)
	at org.gradle.internal.metaobject.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:96)
	at org.gradle.internal.metaobject.MixInClosurePropertiesAsMethodsDynamicObject.invokeMethod(MixInClosurePropertiesAsMethodsDynamicObject.java:30)
	at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:163)
	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:83)
	at build_110a6jhrbdrez539prz5pu5yb.run(E:\WatermelonDiaryNew-master\app\build.gradle:22)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
